import Head from "next/head";

import DashLayout from "@/components/layouts/dashLayout";
import AllProducts from "@/components/products/allProducts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full min-w-[1100px] py-2 pl-4 ">
        <AllProducts />
      </div>
    </>
  );
}

// Home.requireAuth = true;
Home.getLayout = (page) => <DashLayout> {page} </DashLayout>;
